force-app/main/default/objects/Contact/fields/ContactType__c.field-meta.xml
<CustomField>
    <fullName>ContactType__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/DateOfBirth__c.field-meta.xml
<CustomField>
    <fullName>DateOfBirth__c</fullName>
    <label>Date of birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EmployeeContact__c.field-meta.xml
<CustomField>
    <fullName>EmployeeContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/MobilePhone__c.field-meta.xml
<CustomField>
    <fullName>MobilePhone__c</fullName>
    <label>Mobile Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/JobApplicationForm__c/JobApplicationForm__c.object-meta.xml
<CustomObject>
    <label>Job Application Form</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Application Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobApplicationForm__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email address</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/JobApplicationFormController.cls
public class JobApplicationFormController {
	public JobApplicationForm__c form {get;set;}
	public List<Skill> skills {get;set;}
	public Boolean addNewSkill {get;set;}
	public String skillName {get;set;}
	public String skillLevel {get;set;}
	public String skillToRemove {get;set;}

	public JobApplicationFormController() {
		this.form = new JobApplicationForm__c();
		this.skills = new List<Skill>();
	}

	public PageReference submit() {
		Contact contact = new Contact();
		contact.FirstName__c = this.form.FirstName__c;
		contact.LastName__c = this.form.LastName__c;
		contact.Phone = this.form.MobilePhone__c;
		contact.HomePhone = this.form.HomePhone__c;
		contact.Email = this.form.Email__c;
		contact.ContactType__c = 'Employee';
		insert contact;

		Employee__c employee = new Employee__c();
		employee.Name = contact.Name;
		employee.DateOfBirth__c = this.form.DateOfBirth__c;
		employee.Email__c = this.form.Email__c;
		employee.Phone__c = this.form.MobilePhone__c;
		employee.HomePhone__c = this.form.HomePhone__c;
		employee.EmployeeContact__c = contact.Id;
		insert employee;
		PageReference page = new PageReference('/' + employee.Id);
		page.setRedirect(true);
		return page;
	}

	public void addSkill() {
		if (this.skills.size() < 10) {
			this.addNewSkill = true;
		}
	}

	public void removeSkill() {
		System.debug(this.skillToRemove);
	}

	public void save() {
		Skill skill = new Skill();
		skill.name = this.skillName;
		skill.level = this.skillLevel;
		this.skills.add(skill);
		
		this.addNewSkill = false;
		this.skillName = '';
		this.skillLevel = '';
	}

	public class Skill {
		public String name {get;set;}
		public String level {get;set;}
	}
}